name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed


concurrency: preview-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-v32-${{ hashFiles('yarn.lock') }}
      - name: install deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: BUild
        env:
          VITE_BUILD_ENV: development
        run: yarn build
      - name: Deploy preview1
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist/
          deploy-repository: akoidan/vue3-vite-pr-test
          token: ${{ secrets.PR_PAT_TOKEN }}
